import pytest

from tools.render_diagrams import (
    ValidationError,
    build_region,
    d2_labels,
    extract_region,
    inject,
    markers_in,
    open_marker,
    sha256_text,
    source_labels,
    validate_d2_source,
    verify_labels_present,
)


def test_d2_labels_reads_node_and_edge_labels():
    text = 'a: Arco server\nb: Control\na -> b: /game/join\n'
    assert d2_labels(text) == ["Arco server", "Control", "/game/join"]


def test_d2_labels_strips_quotes():
    assert d2_labels('a -> b: "cc:74 -> hue"') == ["cc:74 -> hue"]


def test_d2_labels_strips_a_container_brace():
    assert d2_labels("box: Terrarium box {") == ["Terrarium box"]


def test_d2_labels_skips_styling_keywords():
    text = "a: Arco\na.shape: circle\na.style.fill: red\ndirection: down\n"
    assert d2_labels(text) == ["Arco"]


def test_d2_labels_skips_comments_and_blank_lines():
    assert d2_labels("# a comment\n\na: Arco\n") == ["Arco"]


def test_source_labels_dispatches_to_seqrender():
    got = source_labels("seq", "participants: A, B\nA -> B: /game/hello\n")
    assert got == ["/game/hello"]


def test_validate_rejects_a_newline_inside_a_label():
    """Measured to corrupt D2's box grid: spec section 1.2."""
    with pytest.raises(ValidationError) as exc:
        validate_d2_source("topology", 'arco: Arco server\\n(o2 hub)')
    assert "topology" in str(exc.value)
    assert "\\n" in str(exc.value)


def test_validate_rejects_sequence_diagram_shape():
    """D2's sequence renderer corrupts every slash-bearing label."""
    with pytest.raises(ValidationError) as exc:
        validate_d2_source("flow", "shape: sequence_diagram\na: A\n")
    assert "seqrender" in str(exc.value)


def test_validate_accepts_a_clean_source():
    validate_d2_source("topology", "a: Arco\na -> b: /game/join\n")


def test_round_trip_passes_when_every_label_survives():
    verify_labels_present("topology", "d2", ["/game/join", "Arco"], "box /game/join -> Arco")


def test_round_trip_catches_the_measured_d2_slash_corruption():
    """D2 rendered '/abc' as 'abc' on right-to-left arrows. Spec section 1.2."""
    with pytest.raises(ValidationError) as exc:
        verify_labels_present("flow", "d2", ["/abc"], "|<-----abc------|")
    assert "/abc" in str(exc.value)
    assert "flow" in str(exc.value)
    assert "d2" in str(exc.value)


def test_round_trip_catches_a_silently_dropped_message():
    """Diagon dropped a '//' message and every message after it."""
    with pytest.raises(ValidationError):
        verify_labels_present("flow", "seq", ["/a", "//b", "/c"], "only /a here")


def test_round_trip_reports_the_first_missing_label_only():
    with pytest.raises(ValidationError) as exc:
        verify_labels_present("d", "d2", ["gone", "also-gone"], "")
    assert "gone" in str(exc.value)
    assert "also-gone" not in str(exc.value)


def test_round_trip_names_the_regenerate_command():
    with pytest.raises(ValidationError) as exc:
        verify_labels_present("d", "d2", ["x"], "")
    assert "shorten" in str(exc.value).lower()


DOC = """\
# Title

Some prose.

<!-- diagram:topology GENERATED by tools/render_diagrams.py -- do not hand-edit -->
```ascii
old
```
<!-- /diagram:topology -->

More prose.
"""


def test_sha256_text_is_stable():
    assert sha256_text("abc") == sha256_text("abc")
    assert sha256_text("abc") != sha256_text("abd")


def test_build_region_wraps_in_markers_and_an_ascii_fence():
    region = build_region("topology", "BOX\n")
    assert region.startswith(open_marker("topology"))
    assert "```ascii\nBOX\n```" in region
    assert region.rstrip().endswith("<!-- /diagram:topology -->")


def test_inject_replaces_only_the_marked_region():
    out = inject(DOC, "topology", "NEW\n")
    assert "NEW" in out
    assert "old" not in out
    assert "Some prose." in out
    assert "More prose." in out


def test_inject_is_idempotent():
    once = inject(DOC, "topology", "NEW\n")
    assert inject(once, "topology", "NEW\n") == once


def test_inject_raises_when_the_marker_is_missing():
    with pytest.raises(ValidationError) as exc:
        inject("# Title\n", "topology", "NEW\n")
    assert "topology" in str(exc.value)


def test_extract_region_round_trips_with_build_region():
    out = inject(DOC, "topology", "NEW\n")
    assert extract_region(out, "topology") == build_region("topology", "NEW\n")


def test_markers_in_finds_every_declared_diagram():
    assert markers_in(DOC) == {"topology"}


def test_markers_in_returns_empty_for_a_doc_with_none():
    assert markers_in("# Title\n\nprose\n") == set()
