direction: down

p1: "1. pre-room stack: o2lite transport"
p2: "2. room stack: Bit"
p3: "3. room stack: Room bridge"
p4: "4. room stack: Room simulators"
p5: "5. room stack: Arco"
p6: "6. process stack: devicelink server, console"
p1 -> p2 -> p3 -> p4 -> p5 -> p6
