direction: down

shroom: Tuneshroom (o2lite)
phone: Phone browser (websocket)
arco: Arco server, "arco"
control: Control+GameServer, "game", "actl"

shroom -> arco: o2lite
phone -> arco: websocket
arco <-> control: o2lite, same box
