"""Render docs/diagrams/ sources to ASCII and SVG, and inject the ASCII into
the deep-dive between HTML-comment markers.

Offline tooling, not runtime. Nothing here is imported by the Control+GameServer.
Spec: docs/superpowers/specs/2026-08-17-ascii-diagram-pipeline-design.md
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

from tools import seqrender


class ValidationError(Exception):
    """A diagram source or its rendered output failed a check."""


_D2_KEYWORDS = {
    "shape", "direction", "style", "fill", "stroke", "stroke-width", "stroke-dash",
    "font-size", "font-color", "near", "icon", "width", "height", "link", "tooltip",
    "class", "constraint", "opacity", "border-radius", "3d", "multiple", "animated",
    "bold", "italic", "underline", "text-transform", "label", "vars", "grid-rows",
    "grid-columns",
}


def d2_labels(text: str) -> list[str]:
    """Every string in a .d2 source that must survive rendering verbatim."""
    out: list[str] = []
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or ":" not in line:
            continue
        key, _, value = line.partition(":")
        if key.strip().split(".")[-1] in _D2_KEYWORDS:
            continue
        value = value.strip()
        if value.endswith("{"):
            value = value[:-1].strip()
        if len(value) >= 2 and value.startswith('"') and value.endswith('"'):
            value = value[1:-1]
        if value:
            out.append(value)
    return out


def source_labels(renderer: str, text: str) -> list[str]:
    if renderer == "d2":
        return d2_labels(text)
    if renderer == "seq":
        return seqrender.labels(seqrender.parse(text))
    raise ValidationError(f"unknown renderer {renderer!r}")


def validate_d2_source(name: str, text: str) -> None:
    """Static rules derived from measured D2 defects (spec section 1.2)."""
    if "shape: sequence_diagram" in text:
        raise ValidationError(
            f"{name}: D2's sequence renderer corrupts labels containing '/', '-' or '.'. "
            f"Use a .seq source rendered by tools/seqrender.py instead."
        )
    for label in d2_labels(text):
        if "\\n" in label:
            raise ValidationError(
                f"{name}: label {label!r} contains a literal \\n, which corrupts D2's "
                f"box grid. Split it into separate nodes."
            )


def verify_labels_present(name: str, renderer: str, labels: list[str], rendered: str) -> None:
    """Assert every source label appears verbatim in the rendered text.

    Renderers in this space corrupt or silently truncate rather than raising.
    This check caught, without knowing about any of them: D2 swallowing '/' from
    right-to-left labels, Diagon dropping a '//' message and everything after it,
    and 'cc:74' mis-parsing into a stray participant.
    """
    for label in labels:
        if label not in rendered:
            raise ValidationError(
                f"{name}: renderer {renderer!r} did not reproduce label {label!r} "
                f"verbatim. Either the renderer corrupted it or it wrapped across "
                f"lines; shorten the label."
            )


_MARKER_RE = re.compile(r"<!--\s*diagram:([A-Za-z0-9_-]+)\s+GENERATED[^>]*-->")


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def open_marker(name: str) -> str:
    return f"<!-- diagram:{name} GENERATED by tools/render_diagrams.py -- do not hand-edit -->"


def close_marker(name: str) -> str:
    return f"<!-- /diagram:{name} -->"


def build_region(name: str, ascii_text: str) -> str:
    body = ascii_text.rstrip("\n")
    return f"{open_marker(name)}\n```ascii\n{body}\n```\n{close_marker(name)}"


def extract_region(markdown: str, name: str) -> str:
    start = markdown.find(open_marker(name))
    close = close_marker(name)
    end = markdown.find(close, start + 1) if start != -1 else -1
    if start == -1 or end == -1:
        raise ValidationError(
            f"marker for diagram {name!r} not found in the target document. "
            f"Add:\n{open_marker(name)}\n```ascii\n```\n{close_marker(name)}"
        )
    return markdown[start : end + len(close)]


def inject(markdown: str, name: str, ascii_text: str) -> str:
    region = extract_region(markdown, name)
    return markdown.replace(region, build_region(name, ascii_text), 1)


def markers_in(markdown: str) -> set[str]:
    return set(_MARKER_RE.findall(markdown))


class RenderError(Exception):
    """A renderer could not be run."""


def render_d2(source: Path, workdir: Path) -> dict[str, str]:
    if shutil.which("d2") is None:
        raise RenderError(
            "d2 is not on PATH and is required to regenerate diagrams.\n"
            "Install it with: brew install d2"
        )
    stem = source.stem
    txt, svg = workdir / f"{stem}.txt", workdir / f"{stem}.svg"
    for target in (txt, svg):
        proc = subprocess.run(
            ["d2", str(source), str(target)], capture_output=True, text=True
        )
        if proc.returncode != 0:
            raise RenderError(f"{stem}: d2 failed\n{proc.stderr.strip()}")
    return {f"out/{stem}.txt": txt.read_text("utf-8"),
            f"out/{stem}.svg": svg.read_text("utf-8")}


def render_seq(source: Path, _workdir: Path) -> dict[str, str]:
    text = source.read_text("utf-8")
    rendered = seqrender.render(seqrender.parse(text))
    return {f"out/{source.stem}.txt": rendered}


_RENDERERS = {"d2": render_d2, "seq": render_seq}


def load_manifest(root: Path) -> dict:
    return json.loads((root / "docs/diagrams/manifest.json").read_text("utf-8"))


def render_all(root: Path, renderers: dict | None = None) -> dict[str, dict[str, str]]:
    """Render every diagram into memory. Writes nothing."""
    renderers = renderers or _RENDERERS
    manifest = load_manifest(root)
    out: dict[str, dict[str, str]] = {}
    with tempfile.TemporaryDirectory() as tmp:
        workdir = Path(tmp)
        for name, entry in manifest["diagrams"].items():
            source = root / "docs/diagrams" / entry["source"]
            text = source.read_text("utf-8")
            renderer = entry["renderer"]
            if renderer == "d2":
                validate_d2_source(name, text)
            rendered = renderers[renderer](source, workdir)
            ascii_text = rendered[f"out/{source.stem}.txt"]
            verify_labels_present(name, renderer, source_labels(renderer, text), ascii_text)
            out[name] = rendered
    return out


def write_all(root: Path, rendered: dict[str, dict[str, str]], manifest: dict) -> None:
    docs = root / "docs/diagrams"

    # Pre-flight: every injection target must already carry the diagram's
    # marker pair. Checked in full, against nothing but what's already on
    # disk, before a single byte is written anywhere below -- otherwise a
    # missing marker discovered mid-loop would leave out/ files and injected
    # markdown from earlier diagrams on disk with no manifest update to
    # record it.
    for name, entry in manifest["diagrams"].items():
        target = entry.get("inject_into")
        if target:
            path = root / target
            extract_region(path.read_text("utf-8"), entry["marker"])

    (docs / "out").mkdir(parents=True, exist_ok=True)
    for name, entry in manifest["diagrams"].items():
        source = docs / entry["source"]
        entry["source_sha256"] = sha256_text(source.read_text("utf-8"))
        entry["outputs"] = {}
        for rel, text in rendered[name].items():
            (docs / rel).write_text(text, encoding="utf-8")
            entry["outputs"][rel] = sha256_text(text)
        target = entry.get("inject_into")
        if target:
            path = root / target
            ascii_text = rendered[name][f"out/{source.stem}.txt"]
            path.write_text(
                inject(path.read_text("utf-8"), entry["marker"], ascii_text),
                encoding="utf-8",
            )
    (docs / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def _is_current(root: Path, rendered: dict, manifest: dict) -> bool:
    for name, entry in manifest["diagrams"].items():
        for rel, text in rendered[name].items():
            path = root / "docs/diagrams" / rel
            if not path.exists() or path.read_text("utf-8") != text:
                return False
        if entry.get("source_sha256") != sha256_text(
            (root / "docs/diagrams" / entry["source"]).read_text("utf-8")
        ):
            return False
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render docs/diagrams sources.")
    parser.add_argument("--root", default=".", help="repository root")
    parser.add_argument("--check", action="store_true",
                        help="report whether outputs are current; write nothing")
    args = parser.parse_args(argv)
    root = Path(args.root)

    try:
        rendered = render_all(root)
    except (ValidationError, RenderError, seqrender.SeqParseError) as exc:
        print(f"render_diagrams: {exc}")
        return 1

    manifest = load_manifest(root)
    if args.check:
        if _is_current(root, rendered, manifest):
            print("render_diagrams: diagrams are current")
            return 0
        print("render_diagrams: diagrams are STALE. Run: python -m tools.render_diagrams")
        return 1

    try:
        write_all(root, rendered, manifest)
    except ValidationError as exc:
        print(f"render_diagrams: {exc}")
        return 1
    print(f"render_diagrams: wrote {len(rendered)} diagram(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
