"""Render docs/diagrams/ sources to ASCII and SVG, and inject the ASCII into
the deep-dive between HTML-comment markers.

Offline tooling, not runtime. Nothing here is imported by the Control+GameServer.
Spec: docs/superpowers/specs/2026-08-17-ascii-diagram-pipeline-design.md
"""

from __future__ import annotations

import hashlib
import re

from tools import seqrender


class ValidationError(Exception):
    """A diagram source or its rendered output failed a check."""


_D2_KEYWORDS = {
    "shape", "direction", "style", "fill", "stroke", "stroke-width", "stroke-dash",
    "font-size", "font-color", "near", "icon", "width", "height", "link", "tooltip",
    "class", "constraint", "opacity", "border-radius", "3d", "multiple", "animated",
    "bold", "italic", "underline", "text-transform", "label", "vars", "grid-rows",
    "grid-columns",
}


def d2_labels(text: str) -> list[str]:
    """Every string in a .d2 source that must survive rendering verbatim."""
    out: list[str] = []
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or ":" not in line:
            continue
        key, _, value = line.partition(":")
        if key.strip().split(".")[-1] in _D2_KEYWORDS:
            continue
        value = value.strip()
        if value.endswith("{"):
            value = value[:-1].strip()
        if len(value) >= 2 and value.startswith('"') and value.endswith('"'):
            value = value[1:-1]
        if value:
            out.append(value)
    return out


def source_labels(renderer: str, text: str) -> list[str]:
    if renderer == "d2":
        return d2_labels(text)
    if renderer == "seq":
        return seqrender.labels(seqrender.parse(text))
    raise ValidationError(f"unknown renderer {renderer!r}")


def validate_d2_source(name: str, text: str) -> None:
    """Static rules derived from measured D2 defects (spec section 1.2)."""
    if "shape: sequence_diagram" in text:
        raise ValidationError(
            f"{name}: D2's sequence renderer corrupts labels containing '/', '-' or '.'. "
            f"Use a .seq source rendered by tools/seqrender.py instead."
        )
    for label in d2_labels(text):
        if "\\n" in label:
            raise ValidationError(
                f"{name}: label {label!r} contains a literal \\n, which corrupts D2's "
                f"box grid. Split it into separate nodes."
            )


def verify_labels_present(name: str, renderer: str, labels: list[str], rendered: str) -> None:
    """Assert every source label appears verbatim in the rendered text.

    Renderers in this space corrupt or silently truncate rather than raising.
    This check caught, without knowing about any of them: D2 swallowing '/' from
    right-to-left labels, Diagon dropping a '//' message and everything after it,
    and 'cc:74' mis-parsing into a stray participant.
    """
    for label in labels:
        if label not in rendered:
            raise ValidationError(
                f"{name}: renderer {renderer!r} did not reproduce label {label!r} "
                f"verbatim. Either the renderer corrupted it or it wrapped across "
                f"lines; shorten the label."
            )


_MARKER_RE = re.compile(r"<!--\s*diagram:([A-Za-z0-9_-]+)\s+GENERATED[^>]*-->")


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def open_marker(name: str) -> str:
    return f"<!-- diagram:{name} GENERATED by tools/render_diagrams.py -- do not hand-edit -->"


def close_marker(name: str) -> str:
    return f"<!-- /diagram:{name} -->"


def build_region(name: str, ascii_text: str) -> str:
    body = ascii_text.rstrip("\n")
    return f"{open_marker(name)}\n```ascii\n{body}\n```\n{close_marker(name)}"


def extract_region(markdown: str, name: str) -> str:
    start = markdown.find(open_marker(name))
    close = close_marker(name)
    end = markdown.find(close, start + 1) if start != -1 else -1
    if start == -1 or end == -1:
        raise ValidationError(
            f"marker for diagram {name!r} not found in the target document. "
            f"Add:\n{open_marker(name)}\n```ascii\n```\n{close_marker(name)}"
        )
    return markdown[start : end + len(close)]


def inject(markdown: str, name: str, ascii_text: str) -> str:
    region = extract_region(markdown, name)
    return markdown.replace(region, build_region(name, ascii_text), 1)


def markers_in(markdown: str) -> set[str]:
    return set(_MARKER_RE.findall(markdown))
